In [91]:
import os
import pandas as pd
from dbfread import DBF

# Set pandas display option to show up to 50 columns
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 500)


# Get the current directory where the Jupyter notebook is located
current_directory = #os.getcwd()

# Get a list of all .dbf files in the directory
dbf_files = sorted([file for file in os.listdir(current_directory) if file.endswith('.DBF')])

print(f'Total file number: {len(dbf_files)}')
print(dbf_files)

Total file number: 87
['ACCCAT.DBF', 'ACCLOG.DBF', 'ACCOUNTS.DBF', 'AREA.DBF', 'ASO.DBF', 'ASODET.DBF', 'ASSEMBLY.DBF', 'BARCODES.DBF', 'BARPRINT.DBF', 'BILLINST.DBF', 'BILLS.DBF', 'BORDERHD.DBF', 'BORDERLN.DBF', 'BUDGETS.DBF', 'CDEMESS.DBF', 'CHEQUEHD.DBF', 'CHEQUELN.DBF', 'CNTYPE.DBF', 'COMMENTS.DBF', 'CONTRHD.DBF', 'CONTRLN.DBF', 'CRDRECON.DBF', 'CRO.DBF', 'CRODET.DBF', 'CROLOG.DBF', 'CRONOTES.DBF', 'CROSTOCK.DBF', 'CRTRANS.DBF', 'CSTRANS.DBF', 'DEBRECON.DBF', 'DETRANS.DBF', 'DOCNUM.DBF', 'DOCUMENT.DBF', 'EXCHANGE.DBF', 'FSTRANS.DBF', 'GLGROUPS.DBF', 'GLTRANS.DBF', 'GRDESCR.DBF', 'HORDERHD.DBF', 'HORDERLN.DBF', 'INSTATE.DBF', 'INVOICE.DBF', 'JNLMES.DBF', 'LAYOUTS.DBF', 'LEDGER.DBF', 'MESSAGES.DBF', 'ORDERREF.DBF', 'PATHS.DBF', 'PAYMNTHD.DBF', 'PAYMNTLN.DBF', 'PORDERHD.DBF', 'PORDERLN.DBF', 'PROJHD.DBF', 'PROJLN.DBF', 'QUOTESHD.DBF', 'QUOTESLN.DBF', 'REPFIELD.DBF', 'REPORTS.DBF', 'REPPAPER.DBF', 'REPS.DBF', 'RMAHD.DBF', 'RMALN.DBF', 'RMASNO.DBF', 'SALESREP.DBF', 'SORDERHD.DBF', 'SORDERLN.DBF', 'SOTRANS.DBF', 'SSTRANS.DBF', 'STDJRNL.DBF', 'STKXFER.DBF', 'STOCK.DBF', 'STOCKCAT.DBF', 'STOCKLOC.DBF', 'STORDER.DBF', 'STTRANS.DBF', 'SWTRANS.DBF', 'TAKEON.DBF', 'TERMS.DBF', 'TEXTPRN.DBF', 'TILLS.DBF', 'TLTRANS.DBF', 'TSTRANS.DBF', 'USERS.DBF', 'WORDERHD.DBF', 'WORDERLN.DBF', 'WSLOC.DBF', 'WSTRANS.DBF']

### All DBS files & columns

In [26]:
for dbf_file in dbf_files:
    # Read the .dbf file
    dbf_path = os.path.join(current_directory, dbf_file)
    table = DBF(dbf_path)
    
    # Convert DBF to pandas DataFrame
    df = pd.DataFrame(iter(table))
    
    # Print the name of the file
    print(f"File Name: {dbf_file}")
    
    # Print the column names
    print("Column Names:", df.columns.tolist())
    
    # Print the first 10 rows of the DataFrame
    # print("First 10 Rows:\n", df.head(10))
    # print("\n" + "="*40 + "\n")

File Name: ACCCAT.DBF
Column Names: ['CATEGORY', 'DESCRIP']
File Name: ACCLOG.DBF
Column Names: ['ACCNO', 'USER', 'DATE', 'TIME', 'DESCRIP', 'REASON']
File Name: ACCOUNTS.DBF
Column Names: ['ACCNO', 'ACTYPE', 'GLGROUP', 'TITLE', 'INIT', 'NAME', 'ADDR1', 'ADDR2', 'ADDR3', 'CODE', 'DNAME', 'DADDR1', 'DADDR2', 'DADDR3', 'DCODE', 'DINSTR', 'DISC', 'RETAIL', 'TEL', 'FAX', 'CONTACT', 'TAXNO', 'LANG', 'CRDATE', 'MEMO', 'DELIMIT', 'OPENBAL', 'PERIOD01', 'PERIOD02', 'PERIOD03', 'PERIOD04', 'PERIOD05', 'PERIOD06', 'PERIOD07', 'PERIOD08', 'PERIOD09', 'PERIOD10', 'PERIOD11', 'PERIOD12', 'PERIOD13', 'PERIOD14', 'PERIOD15', 'PERIOD16', 'PERIOD17', 'PERIOD18', 'PERIOD19', 'PERIOD20', 'PERIOD21', 'PERIOD22', 'PERIOD23', 'PERIOD24', 'PERIOD25', 'FOPENBAL', 'FPERIOD01', 'FPERIOD02', 'FPERIOD03', 'FPERIOD04', 'FPERIOD05', 'FPERIOD06', 'FPERIOD07', 'FPERIOD08', 'FPERIOD09', 'FPERIOD10', 'FPERIOD11', 'FPERIOD12', 'FPERIOD13', 'FPERIOD14', 'FPERIOD15', 'FPERIOD16', 'FPERIOD17', 'FPERIOD18', 'FPERIOD19', 'FPERIOD20', 'FPERIOD21', 'FPERIOD22', 'FPERIOD23', 'FPERIOD24', 'FPERIOD25', 'PARENT', 'NOTES', 'AREA', 'TERMCODE', 'EMAIL', 'ACTIVE', 'CREDIT', 'BANK', 'BANKACC', 'BANKBRN', 'CATEGORY', 'EXPORT', 'CONTACT1', 'TEL1', 'SECLEVEL', 'EXCODE', 'FINSERIAL', 'PASSWORD', 'DELIVER']
File Name: AREA.DBF
Column Names: []
File Name: ASO.DBF
Column Names: []
File Name: ASODET.DBF
Column Names: []
File Name: ASSEMBLY.DBF
Column Names: []
File Name: BARCODES.DBF
Column Names: []
File Name: BARPRINT.DBF
Column Names: []
File Name: BILLINST.DBF
Column Names: []
File Name: BILLS.DBF
Column Names: []
File Name: BORDERHD.DBF
Column Names: []
File Name: BORDERLN.DBF
Column Names: []
File Name: BUDGETS.DBF
Column Names: []
File Name: CDEMESS.DBF
Column Names: []
File Name: CHEQUEHD.DBF
Column Names: []
File Name: CHEQUELN.DBF
Column Names: []
File Name: CNTYPE.DBF
Column Names: []
File Name: COMMENTS.DBF
Column Names: []
File Name: CONTRHD.DBF
Column Names: []
File Name: CONTRLN.DBF
Column Names: []
File Name: CRDRECON.DBF
Column Names: []
File Name: CRO.DBF
Column Names: []
File Name: CRODET.DBF
Column Names: []
File Name: CROLOG.DBF
Column Names: []
File Name: CRONOTES.DBF
Column Names: []
File Name: CROSTOCK.DBF
Column Names: []
File Name: CRTRANS.DBF
Column Names: ['ENTRY', 'PERIOD', 'CRNO', 'DOCNO', 'GRVNO', 'SUPINV', 'ORDERNO', 'BANKREF', 'DATE', 'REF', 'AMOUNT', 'TAX', 'TAXCODE', 'EXCODE', 'FAMOUNT', 'PAID']
File Name: CSTRANS.DBF
Column Names: []
File Name: DEBRECON.DBF
Column Names: []
File Name: DETRANS.DBF
Column Names: ['ENTRY', 'PERIOD', 'ACCNO', 'DOCNO', 'INVNO', 'DEBORDER', 'ORDERNO', 'DATE', 'REF', 'AMOUNT', 'TAX', 'TAXCODE', 'DEPREF', 'EXCODE', 'FAMOUNT', 'PAID']
File Name: DOCNUM.DBF
Column Names: ['DOCTYPE', 'DESCRIP', 'DOCNO', 'AUTO']
File Name: DOCUMENT.DBF
Column Names: ['ENTRY', 'DOCNO', 'DATE', 'PERIOD', 'DETLINES', 'REPORT', 'CANCELLED', 'HEAD', 'SYSTEM', 'DETAIL', 'DOCNDX', 'DATENDX', 'PERIODNDX']
File Name: EXCHANGE.DBF
Column Names: ['EXCODE', 'CURRENCY', 'DESCRIP', 'SYMBOL', 'RATE', 'PERIOD01', 'PERIOD02', 'PERIOD03', 'PERIOD04', 'PERIOD05', 'PERIOD06', 'PERIOD07', 'PERIOD08', 'PERIOD09', 'PERIOD10', 'PERIOD11', 'PERIOD12', 'PERIOD13', 'PERIOD14', 'PERIOD15', 'PERIOD16', 'PERIOD17', 'PERIOD18', 'PERIOD19', 'PERIOD20', 'PERIOD21', 'PERIOD22', 'PERIOD23', 'PERIOD24', 'PERIOD25']
File Name: FSTRANS.DBF
Column Names: []
File Name: GLGROUPS.DBF
Column Names: ['GROUP', 'DESCRIP']
File Name: GLTRANS.DBF
Column Names: ['ENTRY', 'PERIOD', 'GLNO', 'DATE', 'DOCNO', 'USER', 'REF', 'REFDOCNO', 'AMOUNT', 'TAX', 'TAXCODE', 'BANKREF', 'EXCODE', 'FAMOUNT', 'RECON', 'DEPTRANS']
File Name: GRDESCR.DBF
Column Names: []
File Name: HORDERHD.DBF
Column Names: []
File Name: HORDERLN.DBF
Column Names: []
File Name: INSTATE.DBF
Column Names: []
File Name: INVOICE.DBF
Column Names: []
File Name: JNLMES.DBF
Column Names: []
File Name: LAYOUTS.DBF
Column Names: ['REPORTNME', 'PAPERNAME', 'FIELDNAME', 'STUFFTYPE', 'ISCENTRED', 'PENCOLOR', 'PENMODE', 'PENSTYLE', 'PENWIDTH', 'BRUSHCOLOR', 'BRUSHSTYLE', 'FONTCOLOR', 'FONTHEIGHT', 'FONTNAME', 'FONTPITCH', 'FONTPIX', 'FONTSIZE', 'FONTBOLD', 'FONTITALIC', 'FONTULINE', 'FONTSTOUT', 'ORIGINX', 'ORIGINY', 'UPTOX', 'UPTOY', 'TEXT', 'JUSTIFY', 'XADJ', 'PRINTON', 'CX', 'CY', 'TCX', 'TCY', 'CPI', 'LAYOUTNDX', 'PRINTLEN']
File Name: LEDGER.DBF
Column Names: []
File Name: MESSAGES.DBF
Column Names: []
File Name: ORDERREF.DBF
Column Names: []
File Name: PATHS.DBF
Column Names: []
File Name: PAYMNTHD.DBF
Column Names: ['RECEIPTNO', 'DOCNO', 'REF', 'DATE', 'DEPREF', 'PERIOD', 'UD', 'POS', 'DEPOSITED', 'TILLREF', 'EXCODE', 'DEPACC']
File Name: PAYMNTLN.DBF
Column Names: ['RECEIPTNO', 'LINE', 'ACCNO', 'INVNO', 'AMOUNT', 'DISCOUNT', 'RECEIPTNDX', 'DEPOSITED', 'TAXCODE', 'TAX', 'FAMOUNT', 'FDISCOUNT']
File Name: PORDERHD.DBF
Column Names: ['TYPE', 'DOCNO', 'ORDERNO', 'ODATE', 'RDATE', 'IDATE', 'STATUS', 'ACCNO', 'NAME', 'CHEQUE', 'USER', 'DOCNDX', 'EUSER', 'TIME', 'DINSTR1', 'DINSTR2', 'DINSTR3', 'EXCODE', 'EXRATE', 'REPCODE']
File Name: PORDERLN.DBF
Column Names: ['TYPE', 'DOCNO', 'ORDERNO', 'LINE', 'STOCKNO', 'DESCRIP', 'QTY', 'AMOUNT', 'TAXCODE', 'TAX', 'SORDERNO', 'DOCNDX']
File Name: PROJHD.DBF
Column Names: []
File Name: PROJLN.DBF
Column Names: []
File Name: QUOTESHD.DBF
Column Names: ['TYPE', 'QUOTENO', 'ACCNO', 'NAME', 'ADDR1', 'ADDR2', 'ADDR3', 'PCODE', 'PTYPE', 'CUSTORD', 'DATE', 'REPCODE', 'REPNAME', 'MESS1', 'MESS2', 'MESS3', 'USER', 'EXCODE', 'EXRATE', 'CRONO']
File Name: QUOTESLN.DBF
Column Names: ['QUOTENO', 'LINE', 'STOCKNO', 'GR', 'UNIT', 'QTY', 'AMOUNT', 'TAXCODE', 'TAX', 'DESCRIP', 'QUOTENDX', 'PTYPE']
File Name: REPFIELD.DBF
Column Names: ['REPORTNME', 'FIELDTYPE', 'ARRPOS', 'FIELDNAME', 'DESCRIP', 'LENGTH', 'DECIMALS', 'OLDFIELD']
File Name: REPORTS.DBF
Column Names: ['REPORTNME', 'DESCRIP', 'DOCTYPE']
File Name: REPPAPER.DBF
Column Names: ['REPORTNME', 'PAPERNAME', 'CANCOPY', 'CANFF', 'ISDEFAULT', 'ISTEXT', 'WIDTH', 'HEIGHT', 'CWIDTH', 'LHEIGHT', 'PSIZE', 'MTOP', 'MBOTTOM', 'MLEFT', 'MRIGHT', 'LMTOP', 'LMBOTTOM', 'CMLEFT', 'CMRIGHT', 'DLINES', 'DLPI', 'DTOP', 'LDTOP', 'DHEIGHT', 'COPIES', 'PAPERNDX']
File Name: REPS.DBF
Column Names: ['REPCODE', 'NAME', 'FULLNAME', 'ADDR1', 'ADDR2', 'ADDR3', 'ADDR4', 'TELNO', 'SALES', 'GROSS', 'SALACC', 'CSTACC']
File Name: RMAHD.DBF
Column Names: []
File Name: RMALN.DBF
Column Names: []
File Name: RMASNO.DBF
Column Names: []
File Name: SALESREP.DBF
Column Names: []
File Name: SORDERHD.DBF
Column Names: ['TYPE', 'DOCNO', 'ORDERNO', 'ODATE', 'RDATE', 'IDATE', 'REPCODE', 'STATUS', 'DESCRIP', 'ACCNO', 'CLIENT', 'ADDR1', 'ADDR2', 'ADDR3', 'PCODE', 'CORDER', 'CHECKER', 'REPCNT', 'PTYPE', 'QUOTENO', 'DEL', 'USER', 'EUSER', 'TIME', 'DOCNDX', 'DNAME', 'DADDR1', 'DADDR2', 'DADDR3', 'DINSTR1', 'DINSTR2', 'DINSTR3', 'EXCODE', 'EXRATE', 'DELIVER', 'CONSIGN']
File Name: SORDERLN.DBF
Column Names: ['TYPE', 'DOCNO', 'ORDERNO', 'LINE', 'STOCKNO', 'GROUP', 'QTY', 'AMOUNT', 'TAXCODE', 'TAX', 'COST', 'DESCRIP', 'DOCNDX', 'PTYPE']
File Name: SOTRANS.DBF
Column Names: []
File Name: SSTRANS.DBF
Column Names: []
File Name: STDJRNL.DBF
Column Names: []
File Name: STKXFER.DBF
Column Names: []
File Name: STOCK.DBF
Column Names: ['STOCKNO', 'DESCRIP', 'INSTOCK', 'FAULTY', 'SUPSTOCK', 'SOSTOCK', 'TSTOCK', 'WIPSTOCK', 'CONSTOCK', 'COST', 'SORDER', 'PORDER', 'MINMAX', 'SERIALNO', 'MIN', 'MAX', 'PSTRUC', 'RETAILA', 'RETAILB', 'RETAILC', 'UNIT', 'BINLOC', 'CATEGORY', 'LPCOST', 'LPDATE', 'SUPPCODE', 'SUPPLIER', 'FIRSTACQ', 'SALACC', 'CSTACC', 'TAXCODE', 'PERIOD01', 'PERIOD02', 'PERIOD03', 'PERIOD04', 'PERIOD05', 'PERIOD06', 'PERIOD07', 'PERIOD08', 'PERIOD09', 'PERIOD10', 'PERIOD11', 'PERIOD12', 'PERIOD13', 'PERIOD14', 'PERIOD15', 'PERIOD16', 'PERIOD17', 'PERIOD18', 'PERIOD19', 'PERIOD20', 'PERIOD21', 'PERIOD22', 'PERIOD23', 'PERIOD24', 'PERIOD25', 'STOCKBAR', 'LICOST', 'ISUPPCODE', 'ISUPPLIER', 'DISC', 'FDATE', 'TDATE', 'WARANT', 'XFER', 'ACTIVE', 'PRICELIST', 'MINMARGIN', 'BILLNO', 'ZEROCOST', 'SECLEVEL', 'VARDESCR', 'NOPRICE', 'SUPSTOCKNO', 'ITEMTYPE', 'NEGATIVE', 'WEIGHT', 'PRODBOM']
File Name: STOCKCAT.DBF
Column Names: ['CATEGORY', 'DESCRIP']
File Name: STOCKLOC.DBF
Column Names: ['STOCKNO', 'LOC01', 'LOC02', 'LOC03', 'LOC04', 'LOC05', 'LOC06', 'LOC07', 'LOC08', 'LOC09', 'LOC10', 'LOC11', 'LOC12', 'LOC13', 'LOC14', 'LOC15', 'LOC16', 'LOC17', 'LOC18', 'LOC19', 'LOC20', 'PERIOD01', 'PERIOD02', 'PERIOD03', 'PERIOD04', 'PERIOD05', 'PERIOD06', 'PERIOD07', 'PERIOD08', 'PERIOD09', 'PERIOD10', 'PERIOD11', 'PERIOD12', 'PERIOD13', 'PERIOD14', 'PERIOD15', 'PERIOD16', 'PERIOD17', 'PERIOD18', 'PERIOD19', 'PERIOD20', 'PERIOD21', 'PERIOD22', 'PERIOD23', 'PERIOD24', 'PERIOD25', 'NOTES']
File Name: STORDER.DBF
Column Names: []
File Name: STTRANS.DBF
Column Names: ['ENTRY', 'PERIOD', 'DOCNO', 'DATE', 'STOCKNO', 'QTY', 'REF', 'ORDERNO', 'ACCNO', 'RETAIL', 'COST', 'DISC', 'REP', 'USER', 'LOCATION', 'EXCODE', 'FRETAIL', 'FCOST']
File Name: SWTRANS.DBF
Column Names: []
File Name: TAKEON.DBF
Column Names: ['GLGROUP', 'ACCNO', 'ACTYPE', 'OPENBAL', 'ADAYS000', 'ADAYS030', 'ADAYS060', 'ADAYS090', 'ADAYS120']
File Name: TERMS.DBF
Column Names: ['TERMCODE', 'DESCRIP', 'DAYS', 'MAXDAYS']
File Name: TEXTPRN.DBF
Column Names: ['PRTNAME', 'RESET', 'FORMFEED', 'UNDSTART', 'UNDEND', 'BOLD', 'NORMAL', 'CPI5', 'CPI10', 'CPI17', 'CPI_END', 'LPI6', 'LPI8', 'PORT', 'PAGELENGTH', 'PRTEXT', 'PRTBOLD', 'PRINTQ']
File Name: TILLS.DBF
Column Names: ['TILLNO', 'ACTIVE', 'NEXTREF', 'INUSE', 'SCANNER', 'RECEIPT', 'PRINTER', 'PRINTTYPE', 'USER']
File Name: TLTRANS.DBF
Column Names: []
File Name: TSTRANS.DBF
Column Names: []
File Name: USERS.DBF
Column Names: ['USER', 'USER1', 'USER2']
File Name: WORDERHD.DBF
Column Names: []
File Name: WORDERLN.DBF
Column Names: []
File Name: WSLOC.DBF
Column Names: []
File Name: WSTRANS.DBF
Column Names: []

### STTRANS.DBF > PURCHAN (Purchase records)

In [98]:
# Read and print single file
single_dbf_path = 'STTRANS.DBF'
table = DBF(single_dbf_path)
df = pd.DataFrame(iter(table))

# Print the name of the file
print(f"File Name: {single_dbf_path}")
# Print the column names
print("Column Names:", df.columns.tolist())
# Print the first 10 rows of the DataFrame
df = df.sort_values(by='DOCNO', ascending=False)
# print("First 10 Rows:\n", df.head(10))
# print("\n" + "="*40 + "\n")
df.head()

File Name: STTRANS.DBF
Column Names: ['ENTRY', 'PERIOD', 'DOCNO', 'DATE', 'STOCKNO', 'QTY', 'REF', 'ORDERNO', 'ACCNO', 'RETAIL', 'COST', 'DISC', 'REP', 'USER', 'LOCATION', 'EXCODE', 'FRETAIL', 'FCOST']

,ENTRY,PERIOD,DOCNO,DATE,STOCKNO,QTY,REF,ORDERNO,ACCNO,RETAIL,COST,DISC,REP,USER,LOCATION,EXCODE,FRETAIL,FCOST
6512,I,1,001656,2024-08-05,JL-SF01-GD,30.0,,001615,CTR010,11.00,11.0,0.0,003,BIANCA P,00,00,11.00,0.0
6511,I,1,001655,2024-08-05,ZJ-F03-GD,100.0,,001611,TE0300,11.05,13.0,0.0,003,BIANCA P,00,00,11.05,0.0
6510,I,1,001654,2024-08-05,ZJ-28-C,7.0,,001607,FP0200,42.32,46.0,0.0,001,ESTHER,00,00,42.32,0.0
6509,I,1,001653,2024-08-05,ZJ-YG229A-R,2.0,,001599,PA0400,64.80,72.0,0.0,003,BIANCA P,00,00,64.80,0.0
6508,I,1,001653,2024-08-05,JL-SF01-GD,100.0,,001599,PA0400,9.90,11.0,0.0,003,BIANCA P,00,00,9.90,0.0

In [83]:
df.ENTRY.unique()

array(['I', 'N', 'C', 'G'], dtype=object)

In [99]:
df[df.ACCNO=='KWC000'].sort_values(by='STOCKNO').head()

,ENTRY,PERIOD,DOCNO,DATE,STOCKNO,QTY,REF,ORDERNO,ACCNO,RETAIL,COST,DISC,REP,USER,LOCATION,EXCODE,FRETAIL,FCOST
5615,G,1,000006,2024-06-20,CS-026Y-L,-128.0,UPS24-04-01,000006,KWC000,0.0,279.0,0.0,,BIANCA P,00,00,0.0,0.0
1997,G,1,000001,2023-11-17,CS-026Y-L,-64.0,UNP230903,000001,KWC000,0.0,262.0,0.0,,BIANCA,00,00,0.0,0.0
5616,G,1,000006,2024-06-20,CS-026Y-M,-128.0,UPS24-04-01,000006,KWC000,0.0,247.0,0.0,,BIANCA P,00,00,0.0,0.0
5617,G,1,000006,2024-06-20,CS-026Y-S,-128.0,UPS24-04-01,000006,KWC000,0.0,223.0,0.0,,BIANCA P,00,00,0.0,0.0
3903,G,1,000004,2024-02-28,CS-06B-L,-96.0,UNP-2023-12-04.1,000004,KWC000,0.0,337.0,0.0,,BIANCA P,00,00,0.0,0.0

### SORDERHD.DBF

In [101]:
# Read and print single file
single_dbf_path = 'SORDERHD.DBF'
table = DBF(single_dbf_path)
df = pd.DataFrame(iter(table))

# Print the name of the file
print(f"File Name: {single_dbf_path}")
# Print the column names
print("Column Names:", df.columns.tolist())
# Print the first 10 rows of the DataFrame
# df = df.sort_values(by='DOCNO', ascending=False)
df = df.sort_values(by='ORDERNO', ascending=False)
df.head()

File Name: SORDERHD.DBF
Column Names: ['TYPE', 'DOCNO', 'ORDERNO', 'ODATE', 'RDATE', 'IDATE', 'REPCODE', 'STATUS', 'DESCRIP', 'ACCNO', 'CLIENT', 'ADDR1', 'ADDR2', 'ADDR3', 'PCODE', 'CORDER', 'CHECKER', 'REPCNT', 'PTYPE', 'QUOTENO', 'DEL', 'USER', 'EUSER', 'TIME', 'DOCNDX', 'DNAME', 'DADDR1', 'DADDR2', 'DADDR3', 'DINSTR1', 'DINSTR2', 'DINSTR3', 'EXCODE', 'EXRATE', 'DELIVER', 'CONSIGN']

,TYPE,DOCNO,ORDERNO,ODATE,RDATE,IDATE,REPCODE,STATUS,DESCRIP,ACCNO,CLIENT,ADDR1,ADDR2,ADDR3,PCODE,CORDER,CHECKER,REPCNT,PTYPE,QUOTENO,DEL,USER,EUSER,TIME,DOCNDX,DNAME,DADDR1,DADDR2,DADDR3,DINSTR1,DINSTR2,DINSTR3,EXCODE,EXRATE,DELIVER,CONSIGN
360,O,001617,001617,2024-08-05,2024-08-05,1899-12-30,001,,,MM0200,ON 68 PRETORIA ROAD,T/A MOMENTUS MOMENTS,68 PRETORIA ROAD,RYNFIELD; BENONI,1501,,,3,1,,,ESTHER,ESTHER,15:26,O001617,OLD OWNER: JUDESM@TELKOMSA.NET,ACCOUNT CREATED 23/01/2017,OLD: 7 DOUGLAS AVE,"FARRARMERE, BENONI",,,,00,1.0,C,N
358,O,001616,001616,2024-08-05,2024-08-05,1899-12-30,003,,,PA0400,PRESTIGE AWARDS (PTY) LTD,419 CORK AVE,"FERNDALE, RANDBURG",,,,,1,1,,,BIANCA P,BIANCA P,15:02,O001616,,P.O. BOX 444,FERNDALE 2160,LESLEY/JENNY,JENNY / FIONA,,,00,1.0,C,N
359,I,001656,001615,1899-12-30,1899-12-30,2024-08-05,003,,,CTR010,CLASSIQUE TROPHIES & RESIN,39 GORST AVENUE,PRIMROSE HILL,GERMISTON,1401,,,0,1,,,,,,I001615,,,,,,,,00,1.0,,
356,O,001615,001615,2024-08-05,2024-08-05,1899-12-30,003,I,,CTR010,CLASSIQUE TROPHIES & RESIN,39 GORST AVENUE,PRIMROSE HILL,GERMISTON,1401,,BIANCA P,1,1,000218,,BIANCA P,BIANCA P,14:44,O001615,,,,,SALES@CLASSIQUETROPHIES.CO.ZA,,,00,1.0,C,N
355,O,001614,001614,2024-08-05,2024-08-05,1899-12-30,003,,,TDG020,TAO DESIGNER GLASS,"P.O. BOX 5032, MEADOWDALE","30 GREEN STREET, WITFIELD",,1615,ITEC,,1,1,,,BIANCA P,BIANCA P,14:28,O001614,,,,,,,,00,1.0,C,N

### .DBF to .CSV

In [113]:
## folder
CSV_folder = 'CSV/'

## files locations
STOCK_DBF = 'STOCK.DBF'
SORDERHD_DBF = 'SORDERHD.DBF'
ACCOUNTS_DBF = 'ACCOUNTS.DBF'
STTRANS_DBF = 'STTRANS.DBF'

dbf_files = [STOCK_DBF, SORDERHD_DBF, ACCOUNTS_DBF, STTRANS_DBF]

In [116]:
# Read convert to pandas df
for i in dbf_files:
    table = DBF(i)
    df = pd.DataFrame(iter(table))
    df.to_csv(CSV_folder + i.split('.')[0] + '.CSV', index=False)
    # print(CSV_folder + i.split('.')[0] + '.CSV')